# Generated by Django 4.2.1 on 2023-05-05 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('words_matched', models.IntegerField()),
                ('longest_word', models.IntegerField()),
                ('most_valuable_word', models.CharField(max_length=20)),
                ('date_played', models.DateTimeField(blank=True, default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('games_played', models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
    ]
