# Generated by Django 4.2.1 on 2023-05-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_game_date_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='game.player'),
            preserve_default='True',
        ),
    ]
