# Generated by Django 4.2.1 on 2023-05-07 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_remove_player_games_played_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='date_played',
            field=models.DateField(blank=True, default=datetime.date.today, null='True'),
        ),
        migrations.AlterField(
            model_name='game',
            name='longest_word',
            field=models.IntegerField(blank=True, null='True'),
        ),
        migrations.AlterField(
            model_name='game',
            name='most_valuable_word',
            field=models.CharField(blank=True, max_length=20, null='True'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='words_matched',
            field=models.IntegerField(blank=True, null='True'),
        ),
    ]
